# Generated by Django 4.0.3 on 2022-04-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_info', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
