# Generated by Django 4.0.3 on 2022-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classs',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
