# Generated by Django 4.0.3 on 2022-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_alter_school_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='has_school',
            field=models.BooleanField(default=False),
        ),
    ]
