# Generated by Django 4.0.3 on 2022-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_teacher_has_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access_token',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
