# Generated by Django 4.0.3 on 2022-04-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0004_student_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='access_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
